name: Workflow B - Triggered by Workflow A

on:
  workflow_dispatch:

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Workflow B triggered by Workflow A, using ref ${{ github.ref_name }}"
