name: Workflow A - Trigger Workflow B

on:
  push:
    branches: [master, main]

jobs:
  trigger_workflow_b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - run: sbt ciReleaseTagNextVersion
      - name: Export ENV vars
        run: echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Trigger Workflow B
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/workflow-b.yml/dispatches \
            -d '{"ref":"${{ env.LATEST_TAG }}"}'
